apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: martindekov-examplefun
  namespace: openfaas-fn
spec:
  encryptedData:
    key: AgAV8En4dp9JCydGI1uyHomfOMYLE1YT/QMilpxTnGPBPKIQngl6NnOjc+vLGQGCCmEglhG1dSA3I0PEZ3Kmhi1yhwYeHmLsf3RUhPXaLAf8aN+itz8V9xMQH4Sp+l9xVZ0wTOCQqTahPBFvCHY6s/AgAE+eo3kOMBkw4dyqVDBJIK7+j4GZISKPB3fdOj8/3x+UM4qvICr8nB0aTw8wnTSRuvDkps/3a+6nwRFZtQs7NV0l/0xVxPOqYORAoKnyIm/A9fYzVGcaZXOerHA5LK+QJkwCy9fIdzfi8VKNxLvrUFbt7uIvk0ue/3YqPeZ9EM5IfvoeGnD1sSCIyK5BSv82KD5WI69Zqj8+hCBaz24CsqtnYuzpeH8Ik7flej9240wz/N//z2s7qximtACtp41cDGE1ZxByJboAVKtKhdNWIa92hLHJwGKdKwlwAJ49VX9PGUiSQkTQ6K36U+DQJYiOZgEJ9f6nXdAIs0hSi39/QHtx996ALv8QGg0Tn+OcnR4ZgEaoEdHNFuzdl0oJRI84y+8kqOsZV/4AGoelxW4iuryXRKo26x0EYxl0PvDqLPuThwkqwSyqsPilJO8ytWuMzFxaF9A5gS+TLUj5LuqOQUJUhn/B8natumXP+KW4KJKgib3YbZMFmIY+Krph7c9pQQG6RMYCYf8gpEuWn+3om4+N1VGbPTOtwZWl5yZiiyTaV18=

